#!/usr/bin/ruby

vpn_bin = "/opt/cisco/anyconnect/bin/vpn"
notif_bin = "terminal-notifier"
curr_path = File.dirname(__FILE__)+"/"
@avat_file = curr_path + 'avatar.png'
discncting = '"Disconnecting VPN..."'
disconectd = '"VPN disconnected."'
failed = '"Disconnecting VPN failed."'

def isConnected(vpn_bin)
  `#{vpn_bin} state` =~ /state: Connected/
end

def notify(alrdy, notif_bin, exec = nil)
  cmd = "#{notif_bin} -title VPNC -message #{alrdy} -appIcon #{@avat_file}"
  if exec
    cmd += " -execute " + exec
  end
  `#{cmd}`
end

notify(discncting, notif_bin)
`#{vpn_bin} disconnect`
if isConnected vpn_bin
  notify(failed, notif_bin)
else
  notify(disconectd, notif_bin)
end


